#!/bin/sh

export PATH="$HOME/.local/bin:$PATH"

# Source system xinitrc scripts
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fcitx5 -d
dmenu-clipd &
dunst &

# Start status bar
while true; do
    slstatus
    sleep 1
done &

feh --no-fehbg --bg-fill ~/wallpapers/sushi_original.png &
exec dwm
