# Generated by `nixos-generate-config' on nixos-btw, then run through
# nixfmt. Do not hand-edit: make changes in ./default.nix instead.
#
# This is a SNAPSHOT. The UUIDs below are true for as long as these disks
# are not reformatted, which is the price of a repository that carries a
# real host. Refresh it on the machine with:
#
#   nixos-generate-config --show-hardware-config \
#     | nixfmt > hosts/nixos-btw/hardware-configuration.nix
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/19d8bb76-b0b2-435e-a73a-5c9b297d3d39";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/AEA5-9120";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/c0b1db63-4917-4d32-b5fb-d9e713a01390"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
