# Host configuration for THIS machine ("artix-btw"):
#
#   * Intel TigerLake laptop -- i5-1135G7 (8 threads), Iris Xe Graphics
#   * 16 GiB RAM, NVMe SSD
#   * Battery BAT1 (matches slstatus), intel_backlight, kbd backlight n/a
#   * Intel WiFi + Bluetooth (hci0)
#   * Displays: internal eDP-1 @60 Hz + external DP-1 @180 Hz
#
# Layering: this file holds HARDWARE-specific decisions; everything
# desktop-related comes from programs.suckless-environment in the module.
#
# Install usage: copy to /etc/nixos/hosts/ and import it from
# configuration.nix instead of (or next to) hosts/minimal.nix.
{
  config,
  pkgs,
  ...
}:

{
  imports = [
    ../nix/module.nix
    # ./hardware-configuration.nix  # <- generated by nixos-generate-config
  ];

  networking.hostName = "artix-btw";

  # ------------------------------------------------------------------
  # Intel platform (TigerLake)
  # ------------------------------------------------------------------

  # CPU microcode updates.
  hardware.cpu.intel.updateMicrocode = true;

  # Hardware video acceleration: Iris Xe uses the iHD driver
  # (VA-API decode/encode in browsers, mpv, ffmpeg...).
  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-media-driver
    ];
  };

  # Use the kernel modesetting driver under Xorg (correct choice for
  # Iris Xe; do NOT install the old xf86-video-intel).
  services.xserver.videoDrivers = [ "modesetting" ];

  # TigerLake laptops benefit from Intel's thermal daemon (throttling
  # protection beyond what power-profiles-daemon does).
  services.thermald.enable = true;

  # Weekly TRIM for the NVMe SSD.
  services.fstrim.enable = true;

  # Firmware update tooling (`fwupdmgr refresh && fwupdmgr update`).
  services.fwupd.enable = true;

  # ------------------------------------------------------------------
  # Desktop toggle + user
  # ------------------------------------------------------------------

  programs.suckless-environment.enable = true;

  users.users.you = {
    isNormalUser = true;
    description = "you";
    extraGroups = [
      "wheel"
      "networkmanager"
      "video" # brightness keys (intel_backlight)
      "input" # input devices
    ];
  };

  # Boot straight into Ly instead of startx from the TTY:
  # services.displayManager.ly.enable = true;

  # Personal apps:
  # programs.suckless-environment.extraPackages = with pkgs; [ discord steam ];

  # Optional extras for a 16 GiB laptop:
  # zramSwap.enable = true;

  # Machine-specific session setup goes in ~/.config/suckless/autostart.sh
  # (see README). For THIS machine:
  #
  #   xrandr --output eDP-1 --mode 1920x1080 --rate 60 --pos 0x0 \
  #          --output DP-1 --primary --mode 1920x1080 --rate 180 --pos 1920x0
  #   xdotool mousemove 2880 540
  #   feh --no-fehbg --bg-fill ~/wallpapers/<wallpaper>

  system.stateVersion = "25.05";
}
