# Template for a MINIMAL NixOS machine running this suckless environment.
#
# Fresh-install flow:
#   1. nixos-generate-config --root /mnt
#   2. Put this repo at /mnt/etc/nixos/suckless-environment (branch: nixos)
#   3. Merge into /mnt/etc/nixos/configuration.nix:
#        imports = [ ./suckless-environment ];
#        programs.suckless-environment.enable = true;
#   4. nixos-install && reboot
#   5. Log in on the TTY and run:  startx
{
  config,
  pkgs,
  ...
}:

{
  imports = [
    ../nix/module.nix
    # ./hardware-configuration.nix  # <- generated by nixos-generate-config; import yours here
  ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking.hostName = "minimal";

  users.users.you = {
    isNormalUser = true;
    description = "you";
    extraGroups = [
      "wheel"
      "networkmanager"
      "video" # brightness keys
      "input" # keyboard backlight
    ];
  };

  programs.suckless-environment.enable = true;

  # Personal apps, riding along with the environment:
  # programs.suckless-environment.extraPackages = with pkgs; [ discord steam ];

  # Boot straight into Ly instead of using startx from the TTY:
  # services.displayManager.ly.enable = true;

  # Machine-specific session setup (monitors, wallpaper) lives in
  # ~/.config/suckless/autostart.sh -- see README "Autostart hook".

  # Set this to the NixOS release you FIRST installed; do not change it
  # afterwards without reading the release notes.
  system.stateVersion = "25.05";
}
