# Template for a MINIMAL NixOS machine running this suckless environment.
#
# Fresh-install flow (channels, no flakes needed):
#   1. Boot the NixOS minimal ISO, partition + mount, then
#        nixos-generate-config --root /mnt
#   2. Put this repo at /mnt/etc/nixos/suckless-environment
#   3. Merge into /mnt/etc/nixos/configuration.nix:
#        imports = [ ./suckless-environment ];   # merge with existing imports
#        programs.suckless-environment.enable = true;
#   4. nixos-install && reboot
#   5. Log in on the TTY and run:  startx
{
  config,
  pkgs,
  ...
}:

{
  imports = [
    ../nix/module.nix
    # ./hardware-configuration.nix  # <- generated by nixos-generate-config; import yours here
  ];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking.hostName = "minimal";

  users.users.you = {
    isNormalUser = true;
    description = "you";
    extraGroups = [
      "wheel"
      "networkmanager"
    ];
  };

  programs.suckless-environment.enable = true;

  # Set this to the NixOS release you FIRST installed; do not change it
  # afterwards without reading the release notes.
  system.stateVersion = "25.05";
}
